import pdf from "@/common/assets/images/pdf.svg";
import world from "@/common/assets/images/world.svg";
import excel from "@/common/assets/images/excel.svg";
import power from "@/common/assets/images/power.svg";

export const FILES_SESSION_DATA = [
  {
    id: 1,
    fileName: "Company Goals 2024.pdf",
    fileType: pdf,
    intraction: "12,453",
    users: "892",
    sensitivity: "Highly Confidential",
    path: "/corporate-strategy/2025-vision/initiatives/",
  },
  {
    id: 2,
    fileName: "Q1 Plan and Projections.xlsx",
    fileType: excel,
    intraction: "8,356",
    users: "605",
    sensitivity: "Confidential",
    path: "/corporate-strategy/2025-vision/initiatives/",
  },
  {
    id: 3,
    fileName: "Employee Onboarding Guide.docx",
    fileType: world,
    intraction: "5321",
    users: "102",
    sensitivity: "Confidential",
    path: "/corporate-strategy/2025-vision/initiatives/",
  },
  {
    id: 4,
    fileName: "Annual Report 2023.pdf",
    fileType: pdf,
    intraction: "420",
    users: "305",
    sensitivity: "Medium",
    path: "/finance/quarterly-reports/Q4-2023/",
  },
  {
    id: 5,
    fileName: "IT Security Policies.pdf",
    fileType: pdf,
    intraction: "315",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 6,
    fileName: "Marketing Campaign Calendar.xlsx",
    fileType: excel,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 7,
    fileName: "Quarterly Budget Review.pptx",
    fileType: power,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 8,
    fileName: "Product Launch Plan.docx",
    fileType: world,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 9,
    fileName: "Client Presentation Template.pptx",
    fileType: power,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 10,
    fileName: "Team Contact List.xlsx",
    fileType: excel,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 11,
    fileName: " Project Kickoff Meeting Agenda.docx",
    fileType: world,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 12,
    fileName: "Sales Forecast Q2 2024.xlsx",
    fileType: excel,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 13,
    fileName: "Employee Performance Review Template.docx",
    fileType: world,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 14,
    fileName: "Strategic Planning Session Notes.pdf",
    fileType: pdf,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
  {
    id: 15,
    fileName: " Customer Satisfaction Survey Results.xlsx",
    fileType: excel,
    intraction: "12",
    users: "892",
    sensitivity: "None",
    path: "/innovation/lab-notes/drug-trial-21/",
  },
];
